general:
  data_path: /Competition/NLP/naturallanguageprocessingcompetition-nlp-1/data
  model_name: digit82/kobart-summarization
  output_dir: /Competition/NLP/naturallanguageprocessingcompetition-nlp-1/submission_exp4
inference:
  batch_size: 32
  ckt_path: model ckt path
  early_stopping: true
  generate_max_length: 100
  length_penalty: 0.6  # GNMT 길이 정규화 (Exp #4)
  no_repeat_ngram_size: 2
  num_beams: 4
  remove_tokens:
  - <usr>
  - <s>
  - </s>
  - <pad>
  result_path: ./prediction/
tokenizer:
  bos_token: <s>
  decoder_max_len: 100
  encoder_max_len: 768  # 512 → 768 (Exp #4)
  eos_token: </s>
  special_tokens:
  - '#Person1#'
  - '#Person2#'
  - '#Person3#'
  - '#PhoneNumber#'
  - '#Address#'
  - '#PassportNumber#'
training:
  do_eval: true
  do_train: true
  early_stopping_patience: 3
  early_stopping_threshold: 0.001
  evaluation_strategy: epoch
  fp16: true
  generation_max_length: 100
  gradient_accumulation_steps: 3  # 1 → 3 (effective batch: 24×3=72)
  gradient_checkpointing: true  # Tier 1 최적화: 메모리 ~30% 절감
  learning_rate: 1.0e-05  # Baseline LR 유지
  load_best_model_at_end: true
  logging_dir: ./logs
  logging_strategy: epoch
  lr_scheduler_type: cosine
  num_train_epochs: 20
  optim: adamw_torch
  overwrite_output_dir: true
  per_device_eval_batch_size: 24  # 32 → 24 (메모리 절약)
  per_device_train_batch_size: 24  # 50 → 24 (OOM 해결, 2.08배 감소)
  predict_with_generate: true
  report_to: none  # Wandb 비활성화
  save_strategy: epoch
  save_total_limit: 5
  seed: 42
  warmup_ratio: 0.1
  weight_decay: 0.01
wandb:
  entity: bkan-ai
  name: kobart-exp4-length-norm-768
  project: dialogue-summarization-competition