_wandb:
    value:
        cli_version: 0.22.2
        e:
            8l2m80osvsnmed5bhgmchvh11eaacx36:
                codePath: notebooks/team/CHH/01_baseline.ipynb
                codePathLocal: 01_baseline.ipynb
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.6"
                disk:
                    /:
                        total: "1081101176832"
                        used: "142553366528"
                email: ieyeppo.job@gmail.com
                executable: /home/ieyeppo/.pyenv/versions/nlp_py3_11_9/bin/python
                git:
                    commit: 71899e97a01fb85e59416b6d0ff28542e78d4725
                    remote: git@github.com:iejob/natural-language-processing-competition.git
                gpu: NVIDIA GeForce RTX 4090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-b2b9e31d-4ca9-4907-d713-96771c28a1dd
                host: PotG
                memory:
                    total: "42058579968"
                os: Linux-6.6.87.1-microsoft-standard-WSL2-x86_64-with-glibc2.39
                program: /home/ieyeppo/AI_Lab/natural-language-processing-competition/notebooks/team/CHH/01_baseline.ipynb
                python: CPython 3.11.9
                root: /home/ieyeppo/AI_Lab/natural-language-processing-competition/notebooks/team/CHH
                startedAt: "2025-10-10T00:55:40.643196Z"
                writerId: 8l2m80osvsnmed5bhgmchvh11eaacx36
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 71
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 71
            "3":
                - 2
                - 13
                - 16
            "4": 3.11.9
            "5": 0.22.2
            "6": 4.57.0
            "8":
                - 1
            "12": 0.22.2
            "13": linux-x86_64
api_keys:
    value:
        huggingface_token: ""
        upstage_api_key: up_rMJWNzzBi6YsD47RhwXPWZrZ0JKsT
evaluation:
    value:
        length_penalty: 1
        metrics:
            - rouge
        no_repeat_ngram_size: 2
        num_beams: 4
        rouge_types:
            - rouge-1
            - rouge-2
            - rouge-l
experiment:
    value:
        description: KoBART 기반 베이스라인 모델
        name: baseline_kobart_v1
        timestamp: true
        version: 1.0.0
gpu:
    value:
        cuda_device: 0
        device: cuda
        memory_fraction: 0.9
        mixed_precision: true
inference:
    value:
        batch_size: 32
        early_stopping: true
        length_penalty: 1
        max_length: 100
        min_length: 10
        no_repeat_ngram_size: 2
        num_beams: 4
        temperature: 1
        top_k: 50
        top_p: 0.95
logging:
    value:
        format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
        level: INFO
        log_every_n_steps: 100
        save_to_file: true
model:
    value:
        max_input_length: 512
        max_target_length: 100
        model_type: bart
        name: digit82/kobart-summarization
        use_cache: true
paths:
    value:
        data_dir: ../../../data/raw
        dev_file: ../../../data/raw/dev.csv
        log_dir: ./logs/baseline
        output_dir: ./models/baseline
        submission_dir: ./submissions/baseline
        test_file: ../../../data/raw/test.csv
        train_file: ../../../data/raw/train.csv
        visualization_dir: ./logs/baseline/visualizations
tokenizer:
    value:
        max_length: 512
        name: digit82/kobart-summarization
        padding: max_length
        special_tokens:
            - '#Person1#'
            - '#Person2#'
            - '#Person3#'
            - '#Person4#'
            - '#Person5#'
            - '#Person6#'
            - '#Person7#'
            - '#PhoneNumber#'
            - '#Address#'
            - '#PassportNumber#'
            - '#SSN#'
            - '#CreditCard#'
            - '#CarNumber#'
            - '#Email#'
        truncation: true
training:
    value:
        adam_epsilon: "1e-8"
        batch_size: 16
        early_stopping_patience: 3
        early_stopping_threshold: 0.001
        evaluation_strategy: epoch
        fp16: true
        fp16_opt_level: O1
        gradient_accumulation_steps: 2
        learning_rate: "5e-5"
        load_best_model_at_end: true
        max_grad_norm: 1
        metric_for_best_model: eval_rouge_l
        num_epochs: 10
        optimizer: adamw
        save_strategy: epoch
        save_total_limit: 3
        scheduler_type: linear
        seed: 42
        warmup_ratio: 0.1
        weight_decay: 0.01
wandb:
    value:
        entity: ieyeppo
        mode: online
        name: baseline-kobart
        notes: KoBART 베이스라인 실험
        project: nlp-competition
        tags:
            - baseline
            - kobart
