# ==================== Optuna 최적화 전략 Config ==================== #
# PRD 11: 하이퍼파라미터 최적화
# 학습 시간 단축 후 더 빠른 최적화 가능

optuna:
  # ---------------------- 최적화 설정 (실험 결과 기반 업데이트) ---------------------- #
  n_trials: 20                                            # 권장값: 20 (30→20, Trial 11에서 최적값 발견)
  timeout: 10800                                          # 타임아웃 3시간 (2시간→3시간, 20 trials 여유)
  sampler: tpe                                            # 샘플러 (TPE)
  pruner: median                                          # Pruner (Median)
  n_startup_trials: 5                                     # 시작 시도 횟수
  direction: maximize                                     # 최적화 방향 (maximize)

  # ---------------------- 최적화 메트릭 ---------------------- #
  metric: rouge-l                                         # 최적화 기준 메트릭

  # ---------------------- 파라미터 탐색 범위 (실험 결과 반영) ---------------------- #
  search_space:
    # 학습률 (최적값: 9.14e-5)
    learning_rate:
      type: loguniform                                    # 로그 균등 분포
      low: 1.0e-06                                        # 최소값: 1e-6
      high: 1.0e-04                                       # 최대값: 1e-4 (5e-5→1e-4, 더 높은 범위 탐색)

    # 배치 크기
    batch_size:
      type: categorical                                   # 카테고리
      choices: [8, 16, 32, 50]                            # 선택지

    # Gradient Accumulation Steps
    gradient_accumulation_steps:
      type: categorical                                   # 카테고리
      choices: [1, 2, 4]                                  # 선택지 (1 우선)

    # Weight Decay (최적값: 0.0995)
    weight_decay:
      type: loguniform                                    # 로그 균등 분포
      low: 0.001                                          # 최소값: 0.001 (1e-4→0.001, 더 높은 범위)
      high: 0.1                                           # 최대값: 0.1

    # Warmup Ratio (최적값: 0.00136, 거의 0에 가까움)
    warmup_ratio:
      type: uniform                                       # 균등 분포
      low: 0.0                                            # 최소값: 0.0
      high: 0.15                                          # 최대값: 0.15 (0.2→0.15, 낮은 값 선호)

    # 생성 파라미터 - num_beams (최적값: 4)
    num_beams:
      type: categorical                                   # 카테고리
      choices: [2, 4, 6, 8]                               # 선택지 (3,5,7 → 2,4,6,8)

    # length_penalty (최적값: 0.938)
    length_penalty:
      type: uniform                                       # 균등 분포
      low: 0.6                                            # 최소값: 0.6
      high: 2.0                                           # 최대값: 2.0

    repetition_penalty:
      type: uniform                                       # 균등 분포
      low: 1.0                                            # 최소값: 1.0
      high: 2.0                                           # 최대값: 2.0

    no_repeat_ngram_size:
      type: categorical                                   # 카테고리
      choices: [2, 3, 4]                                  # 선택지
