# ==================== 앙상블 전략 Config ==================== #
# PRD 12: 다중 모델 앙상블 전략
#
# KoBART 중심 앙상블 전략 (최적 성능)
# - KoBART: 58.5 ROUGE-L (주력 모델, 60% 가중치)
# - 기타 모델: 보조 역할 (40% 가중치 분배)

ensemble:
  # ---------------------- 기본 전략 ---------------------- #
  type: weighted              # weighted, voting
  voting_type: hard           # hard, soft (voting 타입일 때만 사용)

  # ---------------------- KoBART 중심 가중치 ---------------------- #
  # 모델 성능 기반 최적 가중치 설정
  weights:
    kobart: 0.60              # 주력 모델 (ROUGE-L: 58.5)
    llama-3.2-korean-3b: 0.20 # 보조 모델 1 (ROUGE-L: ~45)
    qwen3-4b: 0.15            # 보조 모델 2 (ROUGE-L: ~44)
    solar-10.7b: 0.05         # 최소 가중치 (ROUGE-L: ~42)

  # ---------------------- 자동 최적화 (선택) ---------------------- #
  auto_optimize: false        # Dev set 기반 가중치 자동 최적화
  optimization_metric: rouge-l # 최적화 기준 메트릭
  optimization_method: grid_search  # grid_search, optuna
