# ==================== Optuna 최적화 전략 Config ==================== #
# PRD 11: 하이퍼파라미터 최적화
# 학습 시간 단축 후 더 빠른 최적화 가능

optuna:
  # ---------------------- 최적화 설정 ---------------------- #
  n_trials: 30                                            # 시도 횟수 (50 → 30, 시간 단축)
  timeout: 7200                                           # 타임아웃 (2시간)
  sampler: tpe                                            # 샘플러 (TPE)
  pruner: median                                          # Pruner (Median)
  n_startup_trials: 5                                     # 시작 시도 횟수
  direction: maximize                                     # 최적화 방향 (maximize)

  # ---------------------- 최적화 메트릭 ---------------------- #
  metric: rouge-l                                         # 최적화 기준 메트릭

  # ---------------------- 파라미터 탐색 범위 ---------------------- #
  search_space:
    # 학습률
    learning_rate:
      type: loguniform                                    # 로그 균등 분포
      low: 1.0e-06                                        # 최소값: 1e-6
      high: 5.0e-05                                       # 최대값: 5e-5

    # 배치 크기
    batch_size:
      type: categorical                                   # 카테고리
      choices: [8, 16, 32, 50]                            # 선택지

    # Gradient Accumulation Steps
    gradient_accumulation_steps:
      type: categorical                                   # 카테고리
      choices: [1, 2, 4]                                  # 선택지 (1 우선)

    # Weight Decay
    weight_decay:
      type: loguniform                                    # 로그 균등 분포
      low: 0.0001                                         # 최소값: 1e-4
      high: 0.1                                           # 최대값: 0.1

    # Warmup Ratio
    warmup_ratio:
      type: uniform                                       # 균등 분포
      low: 0.0                                            # 최소값: 0.0
      high: 0.2                                           # 최대값: 0.2

    # 생성 파라미터
    num_beams:
      type: categorical                                   # 카테고리
      choices: [3, 5, 7]                                  # 선택지

    repetition_penalty:
      type: uniform                                       # 균등 분포
      low: 1.0                                            # 최소값: 1.0
      high: 2.0                                           # 최대값: 2.0

    no_repeat_ngram_size:
      type: categorical                                   # 카테고리
      choices: [2, 3, 4]                                  # 선택지
