_base_:
    value: ../base/causal_lm.yaml
_name_or_path:
    value: nlpai-lab/kullm-polyglot-12.8b-v2
_wandb:
    value:
        cli_version: 0.22.2
        e:
            dqfjbsm8nh2ynhnzlxjfdgdq7uhxnx6j:
                args:
                    - --mode
                    - full
                    - --models
                    - all
                    - --epochs
                    - "1"
                    - --batch_size
                    - "8"
                    - --learning_rate
                    - "5e-6"
                    - --gradient_accumulation_steps
                    - "1"
                    - --max_train_samples
                    - "1000"
                    - --warmup_ratio
                    - "0.1"
                    - --weight_decay
                    - "0.01"
                    - --max_grad_norm
                    - "1.0"
                    - --label_smoothing
                    - "0.1"
                    - --use_augmentation
                    - --augmentation_methods
                    - back_translation
                    - paraphrase
                    - synonym
                    - turn_shuffle
                    - --augmentation_ratio
                    - "0.05"
                    - --k_folds
                    - "2"
                    - --fold_seed
                    - "42"
                    - --ensemble_strategy
                    - stacking
                    - --use_tta
                    - --tta_strategies
                    - paraphrase
                    - reorder
                    - synonym
                    - mask
                    - --tta_num_aug
                    - "1"
                    - --use_solar_api
                    - --solar_model
                    - solar-1-mini-chat
                    - --prompt_strategy
                    - few_shot_standard
                    - --validate_data_quality
                    - --quality_threshold
                    - "0.7"
                    - --optimize_inference
                    - --optimization_method
                    - quantization
                    - --use_batch_optimization
                    - --num_beams
                    - "4"
                    - --temperature
                    - "0.7"
                    - --top_p
                    - "0.9"
                    - --top_k
                    - "50"
                    - --repetition_penalty
                    - "1.2"
                    - --length_penalty
                    - "1.0"
                    - --no_repeat_ngram_size
                    - "3"
                    - --save_visualizations
                    - --experiment_name
                    - test_full_pipeline_quick
                    - --seed
                    - "42"
                codePath: scripts/train.py
                codePathLocal: scripts/train.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "12.6"
                disk:
                    /:
                        total: "1081101176832"
                        used: "302749990912"
                email: ieyeppo.job@gmail.com
                executable: /home/ieyeppo/.pyenv/versions/nlp_py3_11_9/bin/python
                git:
                    commit: b1c9a43af96206dd7478b5716e858d11ce1ed431
                    remote: git@github.com:iejob/natural-language-processing-competition.git
                gpu: NVIDIA GeForce RTX 4090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-b2b9e31d-4ca9-4907-d713-96771c28a1dd
                host: PotG
                memory:
                    total: "33656340480"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.39
                program: /home/ieyeppo/AI_Lab/natural-language-processing-competition/scripts/train.py
                python: CPython 3.11.9
                root: /home/ieyeppo/AI_Lab/natural-language-processing-competition/wandb
                startedAt: "2025-10-12T16:51:21.775072Z"
                writerId: dqfjbsm8nh2ynhnzlxjfdgdq7uhxnx6j
        m:
            - "1": train/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 5
                - 11
                - 35
                - 49
                - 53
                - 71
                - 95
                - 98
            "2":
                - 1
                - 5
                - 11
                - 35
                - 49
                - 53
                - 71
                - 95
                - 98
            "3":
                - 7
                - 13
                - 15
                - 16
                - 19
                - 66
            "4": 3.11.9
            "5": 0.22.2
            "6": 4.57.0
            "9":
                "1": transformers_trainer
            "10":
                - 20
            "12": 0.22.2
            "13": linux-x86_64
accelerator_config:
    value:
        dispatch_batches: null
        even_batches: true
        gradient_accumulation_kwargs: null
        non_blocking: false
        split_batches: false
        use_seedable_sampler: true
adafactor:
    value: false
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.999
adam_epsilon:
    value: 1e-08
add_cross_attention:
    value: false
architectures:
    value:
        - GPTNeoXForCausalLM
attention_bias:
    value: true
attention_dropout:
    value: 0
auto_find_batch_size:
    value: false
average_tokens_across_devices:
    value: true
bad_words_ids:
    value: null
batch_eval_metrics:
    value: false
begin_suppress_tokens:
    value: null
bf16:
    value: false
bf16_full_eval:
    value: false
bos_token_id:
    value: null
chunk_size_feed_forward:
    value: 0
classifier_dropout:
    value: 0.1
cross_attention_hidden_size:
    value: null
data_seed:
    value: null
dataloader_drop_last:
    value: false
dataloader_num_workers:
    value: 4
dataloader_persistent_workers:
    value: false
dataloader_pin_memory:
    value: true
dataloader_prefetch_factor:
    value: null
dataset:
    value: '{''format_type'': ''instruction'', ''use_instruction_augmentation'': False}'
ddp_backend:
    value: null
ddp_broadcast_buffers:
    value: null
ddp_bucket_cap_mb:
    value: null
ddp_find_unused_parameters:
    value: null
ddp_timeout:
    value: 1800
debug:
    value: []
decoder_start_token_id:
    value: null
deepspeed:
    value: null
disable_tqdm:
    value: false
diversity_penalty:
    value: 0
do_eval:
    value: true
do_predict:
    value: false
do_sample:
    value: false
do_train:
    value: false
dtype:
    value: float16
early_stopping:
    value: false
encoder_no_repeat_ngram_size:
    value: 0
eos_token_id:
    value: 2
eval_accumulation_steps:
    value: null
eval_delay:
    value: 0
eval_do_concat_batches:
    value: true
eval_on_start:
    value: false
eval_steps:
    value: null
eval_strategy:
    value: epoch
eval_use_gather_object:
    value: false
evaluation:
    value: '{''metric'': ''rouge'', ''rouge_types'': [''rouge1'', ''rouge2'', ''rougeL''], ''use_stemmer'': False, ''tokenizer'': ''mecab''}'
experiment:
    value: '{''name'': ''kullm_v2_12.8b_qlora'', ''seed'': 42, ''deterministic'': True, ''use_wandb'': False, ''wandb_project'': ''nlp-competition'', ''wandb_entity'': None, ''wandb_tags'': [], ''tags'': [''kullm'', ''12.8b'', ''qlora'', ''korea-university'', ''korean'']}'
exponential_decay_length_penalty:
    value: null
finetuning_task:
    value: null
forced_bos_token_id:
    value: null
forced_eos_token_id:
    value: null
fp16:
    value: false
fp16_backend:
    value: auto
fp16_full_eval:
    value: false
fp16_opt_level:
    value: O1
fsdp:
    value: []
fsdp_config:
    value:
        min_num_params: 0
        xla: false
        xla_fsdp_grad_ckpt: false
        xla_fsdp_v2: false
fsdp_min_num_params:
    value: 0
fsdp_transformer_layer_cls_to_wrap:
    value: null
full_determinism:
    value: false
generation_config:
    value: null
generation_max_length:
    value: 2048
generation_num_beams:
    value: 1
gradient_accumulation_steps:
    value: 1
gradient_checkpointing:
    value: false
gradient_checkpointing_kwargs:
    value: null
greater_is_better:
    value: true
group_by_length:
    value: false
half_precision_backend:
    value: auto
hidden_act:
    value: gelu
hidden_dropout:
    value: 0
hidden_size:
    value: 5120
hub_always_push:
    value: false
hub_model_id:
    value: null
hub_private_repo:
    value: null
hub_revision:
    value: null
hub_strategy:
    value: every_save
hub_token:
    value: <HUB_TOKEN>
id2label:
    value:
        "0": LABEL_0
        "1": LABEL_1
ignore_data_skip:
    value: false
include_for_metrics:
    value: []
include_inputs_for_metrics:
    value: false
include_num_input_tokens_seen:
    value: "no"
include_tokens_per_second:
    value: false
inference:
    value: '{''batch_size'': 8, ''generate_max_length'': 100, ''temperature'': 0.7, ''do_sample'': True, ''top_p'': 0.9, ''top_k'': 50, ''num_beams'': 1}'
initializer_range:
    value: 0.02
intermediate_size:
    value: 20480
is_decoder:
    value: false
is_encoder_decoder:
    value: false
jit_mode_eval:
    value: false
label_names:
    value: null
label_smoothing_factor:
    value: 0
label2id:
    value:
        LABEL_0: 0
        LABEL_1: 1
layer_norm_eps:
    value: 1e-05
learning_rate:
    value: 5e-06
length_column_name:
    value: length
length_penalty:
    value: 1
liger_kernel_config:
    value: null
load_best_model_at_end:
    value: true
local_rank:
    value: 0
log_level:
    value: passive
log_level_replica:
    value: warning
log_on_each_node:
    value: true
logging:
    value: '{''log_level'': ''INFO'', ''log_dir'': ''logs'', ''save_steps'': 100, ''logging_steps'': 10}'
logging_dir:
    value: experiments/20251013/20251013_001540_test_full_pipeline_quick/model_5_kullm_v2/kullm_v2_12.8b_qlora/logs
logging_first_step:
    value: false
logging_nan_inf_filter:
    value: true
logging_steps:
    value: 10
logging_strategy:
    value: steps
lora:
    value: '{''r'': 16, ''alpha'': 32, ''target_modules'': [''q_proj'', ''k_proj'', ''v_proj'', ''o_proj'', ''gate_proj'', ''up_proj'', ''down_proj''], ''dropout'': 0.05, ''use_qlora'': True}'
lr_scheduler_type:
    value: linear
max_grad_norm:
    value: 1
max_length:
    value: 20
max_position_embeddings:
    value: 2048
max_steps:
    value: -1
metric_for_best_model:
    value: eval_rouge_sum
min_length:
    value: 0
model:
    value: '{''type'': ''causal_lm'', ''checkpoint'': ''nlpai-lab/kullm-polyglot-12.8b-v2'', ''lora'': {''r'': 16, ''lora_alpha'': 32, ''lora_dropout'': 0.05, ''bias'': ''none'', ''task_type'': ''CAUSAL_LM''}, ''size'': ''12.8B'', ''dtype'': ''fp16'', ''chat_template'': ''kullm''}'
model/num_parameters:
    value: 12946032640
model_type:
    value: gpt_neox
mp_parameters:
    value: ""
neftune_noise_alpha:
    value: null
no_cuda:
    value: false
no_repeat_ngram_size:
    value: 0
num_attention_heads:
    value: 40
num_beam_groups:
    value: 1
num_beams:
    value: 1
num_hidden_layers:
    value: 40
num_return_sequences:
    value: 1
num_steps:
    value: global_step301000
num_train_epochs:
    value: 1
optim:
    value: adamw_torch_fused
optim_args:
    value: null
optim_target_modules:
    value: null
output_attentions:
    value: false
output_dir:
    value: experiments/20251013/20251013_001540_test_full_pipeline_quick/model_5_kullm_v2/kullm_v2_12.8b_qlora
output_hidden_states:
    value: false
output_scores:
    value: false
overwrite_output_dir:
    value: true
pad_token_id:
    value: 2
parallelism_config:
    value: null
partial_rotary_factor:
    value: 0.5
past_index:
    value: -1
paths:
    value: '{''train_data'': ''data/raw/train.csv'', ''dev_data'': ''data/raw/dev.csv'', ''test_data'': ''data/raw/test.csv'', ''output_dir'': ''outputs'', ''model_save_dir'': ''models'', ''submission_dir'': ''submissions''}'
peft_config:
    value:
        default:
            auto_mapping: null
            base_model_name_or_path: nlpai-lab/kullm-polyglot-12.8b-v2
            bias: none
            corda_config: null
            eva_config: null
            exclude_modules: null
            fan_in_fan_out: false
            inference_mode: false
            init_lora_weights: true
            layer_replication: null
            layers_pattern: null
            layers_to_transform: null
            lora_alpha: 32
            lora_bias: false
            lora_dropout: 0.05
            megatron_config: null
            megatron_core: megatron.core
            modules_to_save: null
            peft_type: LORA
            qalora_group_size: 16
            r: 16
            revision: null
            runtime_config:
                ephemeral_gpu_offload: false
            target_modules:
                - dense
                - dense_h_to_4h
                - dense_4h_to_h
                - query_key_value
            target_parameters: null
            task_type: CAUSAL_LM
            trainable_token_indices: null
            use_dora: false
            use_qalora: false
            use_rslora: false
per_device_eval_batch_size:
    value: 8
per_device_train_batch_size:
    value: 8
per_gpu_eval_batch_size:
    value: null
per_gpu_train_batch_size:
    value: null
predict_with_generate:
    value: true
prediction_loss_only:
    value: false
prefix:
    value: null
problem_type:
    value: null
project:
    value: huggingface
push_to_hub:
    value: false
push_to_hub_model_id:
    value: null
push_to_hub_organization:
    value: null
push_to_hub_token:
    value: <PUSH_TO_HUB_TOKEN>
ray_scope:
    value: last
remove_invalid_values:
    value: false
remove_unused_columns:
    value: true
repetition_penalty:
    value: 1
report_to:
    value:
        - wandb
restore_callback_states_from_checkpoint:
    value: false
resume_from_checkpoint:
    value: null
return_dict:
    value: true
return_dict_in_generate:
    value: false
rope_scaling:
    value: null
rope_theta:
    value: 10000
rotary_emb_base:
    value: 10000
rotary_pct:
    value: 0.5
run_name:
    value: null
save_on_each_node:
    value: false
save_only_model:
    value: false
save_safetensors:
    value: true
save_steps:
    value: 500
save_strategy:
    value: epoch
save_total_limit:
    value: 2
seed:
    value: 42
sep_token_id:
    value: null
skip_memory_metrics:
    value: true
sortish_sampler:
    value: false
strategies:
    value: '{''data_augmentation'': False, ''cross_validation'': False, ''ensemble'': False, ''optuna'': False}'
suppress_tokens:
    value: null
task_specific_params:
    value: null
temperature:
    value: 1
tf_legacy_loss:
    value: false
tf32:
    value: null
tie_encoder_decoder:
    value: false
tie_word_embeddings:
    value: false
tokenizer:
    value: '{''encoder_max_len'': 1024, ''decoder_max_len'': 200}'
tokenizer_class:
    value: null
top_k:
    value: 50
top_p:
    value: 1
torch_compile:
    value: false
torch_compile_backend:
    value: null
torch_compile_mode:
    value: null
torch_empty_cache_steps:
    value: null
torchdynamo:
    value: null
torchscript:
    value: false
tpu_metrics_debug:
    value: false
tpu_num_cores:
    value: null
trackio_space_id:
    value: trackio
training:
    value: '{''output_dir'': ''experiments/20251013/20251013_001540_test_full_pipeline_quick/model_5_kullm_v2'', ''epochs'': 1, ''batch_size'': 8, ''learning_rate'': 5e-06, ''weight_decay'': 0.1, ''warmup_steps'': 500, ''save_total_limit'': 2, ''logging_steps'': 10, ''num_workers'': 4, ''early_stopping_patience'': 3, ''device'': ''cuda'', ''gradient_accumulation_steps'': 16, ''lr_scheduler_type'': ''cosine'', ''warmup_ratio'': 0.1, ''max_grad_norm'': 1.2, ''gradient_checkpointing'': True, ''fp16'': False, ''bf16'': False}'
transformers_version:
    value: 4.57.0
typical_p:
    value: 1
use_bfloat16:
    value: false
use_cache:
    value: false
use_cpu:
    value: false
use_legacy_prediction_loop:
    value: false
use_liger_kernel:
    value: false
use_mps_device:
    value: false
use_parallel_residual:
    value: true
vocab_size:
    value: 30080
wandb:
    value: '{''enabled'': True, ''project'': ''nlp-competition'', ''entity'': ''ieyeppo''}'
warmup_ratio:
    value: 0
warmup_steps:
    value: 500
weight_decay:
    value: 0.1
